#!/bin/bash

jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension

export DASK_ROOT_CONFIG=/srv/repo/binder/dask_config.yaml
#EOF
