# Note that there must be a tag
FROM pangeo/pangeo-notebook:2020.08.24

# update conda
#RUN conda update -n root conda

# Add NB_USER to sudo
#USER root
#RUN echo "jovyan ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/notebook
