#!/bin/bash

# dask configuration
mkdir -p ${KERNEL_PYTHON_PREFIX}/etc/dask
cp binder/dask_config.yaml ${KERNEL_PYTHON_PREFIX}/etc/dask/dask.yaml

# labextensions
jupyter labextension install @pyviz/jupyterlab_pyviz jupyter-leaflet
