#!/bin/bash

# dask configuration
#mkdir /srv/conda/envs/notebook/etc/dask/
#cp dask_config.yaml /srv/conda/envs/notebook/etc/dask/dask.yaml

# labextensions
jupyter labextension install @pyviz/jupyterlab_pyviz jupyter-leaflet
jupyter labextension install dask-labextension
jupyter serverextension enable dask_labextension
