#!/usr/bin/env bash
# script to send email from CircleCI using SendGrid
# pass as arguments: email address, email subject, email body

# define message attributes
SENDER_EMAIL="no-reply@pangeo.io"
SENDER_NAME="Pangeo"

# send message
curl --url https://api.sendgrid.com/v3/mail/send \
  --header "Authorization: Bearer $SENDGRID_API_KEY" \
  --header "Content-Type: application/json" \
  --data '{"personalizations":[{"to":[{"email":"'"${1}"'"}], "subject":"'"${2}"'"}], \
"from":{"email":"'"${SENDER_EMAIL}"'","name":"'"${SENDER_NAME}"'"}, \
"content": [{"type": "text/plain", "value": "'"${3}"'"}]}'
