#!/usr/bin/env bash

# check number of arguments
if [ "$#" -ne 2 ]; then
    echo "Enter an email address and the email body as two arguments."
    exit
fi

# define message attributes
SENDER_EMAIL="no-reply@pangeo.io"
SENDER_NAME="Pangeo"
SUBJECT="CircleCI Error"
BODY="${2} on `date -u +'%D at %T UTC.'`"

# send message
curl --url https://api.sendgrid.com/v3/mail/send \
  --header "Authorization: Bearer $SENDGRID_API_KEY" \
  --header "Content-Type: application/json" \
  --data '{"personalizations":[{"to":[{"email":"'"${1}"'"}], "subject":"'"${SUBJECT}"'"}], \
"from":{"email":"'"${SENDER_EMAIL}"'","name":"'"${SENDER_NAME}"'"}, \
"content": [{"type": "text/plain", "value": "'"${BODY}"'"}]}'
