#!/bin/bash

jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz@0.6.4 \
                             jupyter-leaflet@0.8.1 \
                             dask-labextension@0.3.0


#EOF
