#!/bin/bash

git clone -b develop https://github.com/ncar/summa.git

cd summa
git checkout -b cewa564_pangeo b074b0
# Add the commit from Andrew that sets the time offset to 0
git cherry-pick 3516fe2

export F_MASTER=${PWD}
export FC="gfortran"
export FC_EXE="gfortran"
export FC_ENV="gfortran-6-docker"

make -C build/ -f Makefile

cd ${HOME}

mkdir -p work
mkdir -p work/homework_0
mkdir -p work/homework_1
mkdir -p junk

#EOF
