#!/bin/bash

git clone -b cuahsi_vu_2019 https://github.com/bartnijssen/summa.git

cd summa

export F_MASTER=${PWD}
export FC="gfortran"
export FC_EXE="gfortran"
export INCLUDES="-I/usr/include"
export LIBRARIES="-L/usr/lib -lnetcdff -llapack -lblas"

make -C build/ -f Makefile

cd ${HOME}

mkdir -p work
mkdir -p work/homework_0
mkdir -p work/homework_1
mkdir -p junk

#EOF
