apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: pangeo-deploy
version: 0.1.0
dependencies:
  - name: daskhub
    version: "4.4.2"
    repository: https://helm.dask.org
    import-values:
      - child: rbac
        parent: rbac
  - name: ingress-nginx
    version: "2.11.3"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: metrics.enabled
  - name: prometheus-operator
    version: "9.3.1"
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: metrics.enabled
