{
 "title": "dask",
 "description": "Monitor an auto-scaling Dask cluster, including a dynamic view of active workers. ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "worker_instance",
    "label": "workers",
    "query": "query_result(max_over_time(dask_worker_threads[${__range_s}s]))"
   },
   { "name": "active_interval", "label": "active interval", "query": "1m,10m,30m,1h,3h,6h,12h,1d" },
   {
    "name": "active_worker_instance",
    "label": "active workers",
    "query": "query_result(max_over_time(dask_worker_threads[$active_interval]))"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(dask_scheduler_clients)" }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dask_scheduler_clients", "legendFormat": "Clients" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "content": "\n# active workers (last $active_interval)"
  },
  {
   "title": "Threads  @ $active_worker_instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "repeat": "active_worker_instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dask_worker_threads{instance=~\"$active_worker_instance\"}"
    }
   ]
  },
  {
   "title": "Tasks @ $active_worker_instance",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "repeat": "active_worker_instance",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dask_worker_tasks{instance=~\"$active_worker_instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Tasks: scheduler",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "dask_scheduler_tasks", "legendFormat": "{{state}}" },
    {
     "expr": "dask_scheduler_tasks_forgotten_total",
     "legendFormat": "forgotten"
    }
   ]
  },
  {
   "title": "Tasks: scheduler",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 3, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dask_scheduler_tasks", "legendFormat": "{{state}}" },
    {
     "expr": "dask_scheduler_tasks_forgotten_total",
     "legendFormat": "forgotten"
    }
   ]
  },
  {
   "title": "Tasks: workers",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(dask_worker_tasks) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Tasks: workers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dask_worker_tasks) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dask_scheduler_workers{state=~\"connected\"})"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dask_scheduler_workers", "legendFormat": "{{state}}" },
    { "expr": "dask_scheduler_desired_workers", "legendFormat": "desired" }
   ]
  },
  {
   "title": "Workers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "dask_scheduler_workers", "legendFormat": "{{state}}" },
    { "expr": "dask_scheduler_desired_workers", "legendFormat": "desired" }
   ]
  },
  {
   "title": "Worker Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dask_worker_connections", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Worker latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(dask_worker_latency_seconds) without (instance)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(dask_worker_latency_seconds) without (instance)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Worker Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 3, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "dask_worker_latency_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}