#!/bin/bash

mkdir -p ${KERNEL_PYTHON_PREFIX}/etc/dask
cp binder/dask_config.yaml ${KERNEL_PYTHON_PREFIX}/etc/dask/dask.yaml

jupyter labextension install dask-labextension

# conda config for user-created environments
cp binder/user-condarc.txt ${KERNEL_PYTHON_PREFIX}/user-condarc.txt
#EOF
