#!/bin/bash

jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            dask-labextension \
                            @pyviz/jupyterlab_pyviz \
                            @jupyterlab/geojson-extension \
                            jupyter-leaflet

# extra dask config
#mkdir ${NB_PYTHON_PREFIX}/etc/dask
#cp dask_config.yaml ${NB_PYTHON_PREFIX}/etc/dask/dask.yaml

#EOF
